name: Build and Push Multiple Docker Images

on:
  push:
    paths:
      - 'Dockerfiles/airflow/**'
      - 'Dockerfiles/fastapi/**'
      - 'Dockerfiles/streamlit/**'
      - 'Dockerfiles/mlflow/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [airflow, fastapi, streamlit, mlflow]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ./Dockerfiles/${{ matrix.service }}
          file: ./Dockerfiles/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
